from enum import Enum, auto

class ImageType(Enum):
    TABLE_IMAGE = auto()
    CELL_NORMAL = auto()
    CELL_HOVER = auto()
    PLAYER = auto()
    BOT = auto()
    PLAY_HOVER = auto()
    PLAY_NORMAL = auto()
    PLAY_DISABLE = auto()
    RESTART_HOVER = auto()
    RESTART_NORMAL = auto()
    RESTART_DISABLE = auto()
    LESS_VOLUME_HOVER = auto()
    LESS_VOLUME_NORMAL = auto()
    PLUS_VOLUME_HOVER = auto()
    PLUS_VOLUME_NORMAL = auto()
    EFFECT_VOLUME_TEXT = auto()
    MUSIC_VOLUME_TEXT = auto()
    PRESS_PLAY = auto()
    PLAYER_WIN = auto()
    PLAYER_MOVE = auto()
    BOT_WIN = auto()
    BOT_MOVE = auto()
    DRAW = auto()
